-- MySQL Script generated by MySQL Workbench
-- 05/12/16 10:05:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BancoCentral
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BancoCentral
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoCentral` DEFAULT CHARACTER SET utf8 ;
USE `BancoCentral` ;

-- -----------------------------------------------------
-- Table `BancoCentral`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoCentral`.`pessoa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoCentral`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoCentral`.`contas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codpessoa` INT(11) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `saldo` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`codigo`),
  UNIQUE KEY `numero` (`numero`),
  INDEX `fk_contas_pessoa1_idx` (`codpessoa` ASC),
  CONSTRAINT `fk_contas_pessoa1`
    FOREIGN KEY (`codpessoa`)
    REFERENCES `BancoCentral`.`pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoCentral`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoCentral`.`usuario` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `nivel` INT(1) NOT NULL,
  `digital` TEXT,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoCentral`.`pessoafisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoCentral`.`pessoafisica` (
  `codpessoa` INT(11) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `datanascimento` DATETIME NOT NULL,
  `sexo` CHAR(1) NOT NULL DEFAULT 'I',
  PRIMARY KEY (`codpessoa`),
  CONSTRAINT `fk_pessoafisica_pessoa`
    FOREIGN KEY (`codpessoa`)
    REFERENCES `BancoCentral`.`pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoCentral`.`pessoajuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoCentral`.`pessoajuridica` (
  `codpessoa` INT(11) NOT NULL,
  `inscricaoestadual` VARCHAR(20) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`codpessoa`),
  CONSTRAINT `fk_pessoajuridica_pessoa1`
    FOREIGN KEY (`codpessoa`)
    REFERENCES `BancoCentral`.`pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
